name: docs
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          git clone https://github.com/squidfunk/mkdocs-material.git
          pip install -r mkdocs-material/requirements.txt
          pip install mike
          pip install mkdocs-git-revision-date-localized-plugin
          git config user.name github-actions
          git config user.email github-actions@github.com
          mike deploy --push --update-aliases 2.2 latest
          mike set-default --push latest
