name: docs
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: git clone https://github.com/squidfunk/mkdocs-material.git
      - run: pip install \
              -r mkdocs-material/requirements.txt \
              mike \
              mkdocs-git-revision-date-localized-plugin
      - run: mike deploy --push --update-aliases 2.2 latest
      - run: mike set-default --push latest
